# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: dist/jowl.spec

# add or remove files that should be synced
files_to_sync:
  - .packit.yaml
  - src:
    - dist/jowl.spec
    - dist/packit-post-upstream-clone.sh
    dest: dist/
    mkpath: true

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: jowl
upstream_tag_template: 'v{version}'
# downstream (Fedora) RPM package name
downstream_package_name: jowl

srpm_build_deps:
  - nodejs-packaging-bundler
  - /usr/bin/node # Hack to work around https://src.fedoraproject.org/rpms/nodejs20/c/92480e045911151ae470f279ceef834f0f5b4370 not yet being released

actions:
  post-upstream-clone:
    - dist/packit-post-upstream-clone.sh

jobs:
- job: copr_build
  trigger: pull_request
  targets: [fedora-all]

- job: tests
  trigger: pull_request
  targets: [fedora-all]

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all
