# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: dist/jowl.spec

# add or remove files that should be synced
files_to_sync:
    - dist/jowl.spec
    - dist/packit-fix-spec-file.sh
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: jowl
upstream_tag_template: 'v{version}'
# downstream (Fedora) RPM package name
downstream_package_name: jowl

srpm_build_deps:
  - nodejs-packaging-bundler

actions:
  fix-spec-file:
    - dist/packit-fix-spec-file.sh

jobs:
- job: copr_build
  trigger: pull_request
  targets: [fedora-all]

- job: tests
  trigger: pull_request
  targets: [fedora-all]

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all
