# Test against all Node versions after 4
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Install the requisite vesion of Node
  - ps: Install-Product node $env:nodejs_version
  # install dependencies
  - yarn install --frozen-lockfile

# Post-install test scripts.
test_script:
  # Output useful info for debugging
  - node --version
  - yarn --version
  # run build
  - yarn run build

# Don't run msbuild
build: off
