# Test against all Node versions after 4
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"

# Install scripts. (runs after repo cloning)
install:
  # Install the requisite vesion of Node
  - ps: Install-Product node $env:nodejs_version
  # install dependencies
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run build
  - npm run build

# Don't run msbuild
build: off
