version: 2.1

workflows:
  all-builds:
    jobs:
      - build:
          matrix:
            parameters:
              os:
                - linux
                - macos
              node-version:
                - "6" # Best effort support
                - "8" # Best effort support
                - "10" # Best effort support
                - "12" # Fully supported
                - "14" # Fully supported
                - "16" # Fully supported

executors:
  linux:
    docker:
      - image: cimg/base:2022.01 # Version chosen arbitrarily as newest at time of writing
  macos:
    macos:
      xcode: 13.2.1 # Version chosen arbitrarily as newest at time of writing

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run build
