version: 2.1

workflows:
  build-node-all:
    jobs:
      - build-node-4
      - build-node-5
      - build-node-6
commands:
  build:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}{{ checksum "yarn.lock" }}

      - run: yarn run build
  install-yarn:
    steps:
      - run: 'npm install -g yarn@1.12' # Newer versions don't seem to work on Node 5

jobs:
  build-node-4:
    docker:
      - image: circleci/node:4
    working_directory: ~/jowl
    steps:
      - build
  build-node-5:
    docker:
      - image: node:5
    working_directory: ~/jowl
    steps:
      - install-yarn
      - build
  build-node-6:
    docker:
      - image: circleci/node:6
    working_directory: ~/jowl
    steps:
      - build

